//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PorjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderDetail
    {
        public int DetialOrder { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public int qty { get; set; }
        public int price { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
